### ISSUE TITLE
Clojurescript support

### ISSUE THREAD

**Issue by kongeor** [trhura/clojure-humanize#10]
It would be nice to have clojurescript support as UIs can really benefit from this library.

With clojure 1.7+ using [reader conditionals](http://clojure.org/guides/reader_conditionals) this [can](https://github.com/kongeor/clojure-humanize/commit/07e1b5304eca020b4855a6a472cfaed9ef7bca06) be [done](https://github.com/kongeor/clojure-humanize/commit/bf4579851b0be3d317d1d9723008e230f90fa10b).

The tests are passing for both clj and cljs.

Should I do some cleanup and make a PR?

**Comment by trhura** [comment]
Sure. Not coding much myself these days. Would be more than willing to accept any PR. Thanks!

**Comment by trhura** [comment]
Merged your PR. Not coding myself much these days - working in a corporate with a windows laptop without even admin permission. :'(

I have added you as a collaborator. Thanks!

**Comment by kongeor** [comment]
Ow man, good luck I guess :S

Thanks for adding me as a collaborator! :)
