### ISSUE TITLE
Loading exception when clj-time 0.11.0 is added to project

### ISSUE THREAD

**Issue by keeth** [trhura/clojure-humanize#11]
create a new project:
```
lein new app humanize-bug
```
add clojure-humanize and clj-time deps to project.clj
```
:dependencies [
  [org.clojure/clojure "1.8.0"]
  [clojure-humanize "0.1.0"]
  [clj-time "0.11.0"]
  ]
```
require humanize in core.clj:
```
(ns humanize-bug.core
  (:gen-class)
  (:require [clojure.contrib.humanize :refer [truncate]]))

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (println (truncate (first args) 5)))
```

`lein run "hello world"`

expected:
`he...`
actual:
```
Exception in thread "main" java.lang.IllegalStateException: to-local-date-time already refers to: #'clj-time.local/to-local-date-time in namespace: clojure.contrib.humanize, compiling:(clojure/contrib/humanize.clj:1:1)
```

**Comment by kongeor** [comment]
I'm preparing cljs support [here](https://github.com/trhura/clojure-humanize/issues/10) which will fix this issue. I will make the PR this weekend.

**Comment by kongeor** [comment]
Thanks for the reproduce plan.

[This](https://github.com/trhura/clojure-humanize/issues/10) has been merged so before 0.1.1 is released you can use [checkout dependencies](https://github.com/trhura/clojure-humanize/issues/10).

**Comment by keeth** [comment]
thanks! appreciate it.

**Comment by kongeor** [comment]
@keeth `0.2.0` has been released. You should be good to go with this version. :)
