### ISSUE TITLE
Release 0.2.0

### ISSUE THREAD

**Issue by kongeor** [trhura/clojure-humanize#13]
Let's release 0.1.1 which will resolve [11](https://github.com/trhura/clojure-humanize/issues/11).

**Comment by kongeor** [comment]
Maybe a bigger version bump is more appropriate here ... something like `0.2.0`.

**Comment by trhura** [comment]
Sure. Feel free to commit and merge. @kongeor

**Comment by kongeor** [comment]
Updated `project.clj`. We are ready to release `0.2.0`. Please do @trhura.

**Comment by trhura** [comment]
clojure-humanize is originally uploaded to clojars by someone else. @nickzam, could you please release 0.2.0 on clojar or add kongeor to the project?

**Comment by nickzam** [comment]
Hi, added kongeor to clojars clojure-humanize group. @kongeor you can release it on your own.

**Comment by kongeor** [comment]
@nickzam Thanks!
