### ISSUE TITLE
Dynamic atoms in clojure.contrib.inflect?

### ISSUE THREAD

**Issue by hlship** [trhura/clojure-humanize#14]
In `clojure.contrib.inflect`, `*pluralize-noun-rules* ` and `*pluralize-noun-exceptions*` are ^:dynamic, but their root values are never rewritten, instead the atoms inside the reference are rewritten.  Is this intentional?  If not, they can be converted to ordinary, non-dynamic, non-earmuff vars.

**Comment by kongeor** [comment]
I agree. This code can be simplified.
