### ISSUE TITLE
Humanize datetimes in the future

### ISSUE THREAD

**Issue by polymeris** [trhura/clojure-humanize#17]
I.e. positive time diffs, like in: "in a moment", "tomorrow", "in 2 days", "next week", or similar.

**Comment by Olical** [comment]
Isn't this what duration is kind of for? Also, I can't access duration. I can see all of the other functions but it's as if it's not in the namespace.

**Comment by kongeor** [comment]
Sorry the delay. 

I will try to release it today.

@polymeris 
Just to be sure that we are on the same page, you are trying to pass a time in the future to `datetime` function, right?

We could do something like "in a moment", "in one day", "in five weeks" etc. seems logical to me.

I'll try to include it in 0.2.1.

**Comment by polymeris** [comment]
Yes, exactly.

**Comment by kongeor** [comment]
0.2.1 is released but I didn't had enough time to implement it. I'll give it a shot this weekend.

**Comment by kongeor** [comment]
Positive time diffs are now supported :)

Note that the algorithm is not that intelligent, so if you have a 4.999 days diff it will describe it as "in 4 days" although its really a 5 day diff.

0.2.2 was just released.

Have fun!

**Comment by Olical** [comment]
Awesome work, thanks @kongeor! :smile:
