### ISSUE TITLE
when will version 0.2.1 be released?

### ISSUE THREAD

**Issue by kp2222** [trhura/clojure-humanize#18]
Thanks a ton for your work on Clojure-humanize!

I just saw that the "duration" function has been recently added to version 0.2.1 . I was just wondering if there is anything blocking you from release this version to Clojars. I will be happy to help if there is something that I can do to help

**Comment by kongeor** [comment]
Sorry for the delay.

Nothing really, just got postponed indefinitely ... I'll try to release it today.

**Comment by kongeor** [comment]
Ready!
