### ISSUE TITLE
Upgrade dependencies for 2020

### ISSUE THREAD

**Issue by ohbadiah** [trhura/clojure-humanize#24]
Hi,

I love the idea of the library. I just tried bringing it in though and I see lein grabbing `clj-time` 0.12.0. We're already bringing in 0.15.2. This sounds just dicey enough to keep me from using the library.

It'd be nice just to give things a once-over and publish a current version.

Let me know if I could help.

**Comment by trhura** [comment]
Could you help submit a PR. I would be happy to merge, as long as the tests are ok. Thanks.

**Comment by hlship** [comment]
Well, we've got modern tooling set up and I'm doing I'm using `antq` to check for outdated deps.  Thanks for the offer!
