### ISSUE TITLE
Oxford isn't oxford

### ISSUE THREAD

**Issue by mgalgs** [trhura/clojure-humanize#7]
`oxford` doesn't seem to actually use an [oxford comma](https://en.wikipedia.org/wiki/Serial_comma).  I believe the correct output would be:

```clojure
user> (clojure.contrib.humanize/oxford ["apple" "orange" "mango"])
"apple, orange, and mango"
```

(Note the comma after `orange` :) )

**Comment by JohnPostlethwait** [comment]
Haha, was just about to file this myself after reading the README.

The style this is outputting is known as AP style.
